---
- name: Deploy WordPress in AWS cloud
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
  - amazon.aws
  tasks:

  - name: Create VPC
    ec2_vpc_net:
      name: wp_lab_vpc
      cidr_block: 10.1.0.0/16
      region: eu-central-1
    register: vpc

  - debug: var=vpc

  - name: Create left subnet
    ec2_vpc_subnet:
      vpc_id: "{{ vpc.vpc.id }}"
      cidr: 10.1.1.0/24
      az: eu-central-1a
      tags:
        Name: wp_lab_subnet_left
    register: subnet_left

  - debug: var=subnet_left

  - name: Create right subnet
    ec2_vpc_subnet:
      vpc_id: "{{ vpc.vpc.id }}"
      cidr: 10.1.2.0/24
      az: eu-central-1b
      tags:
        Name: wp_lab_subnet_right
    register: subnet_right

  - debug: var=subnet_right

  - name: Create Internet gateway
    ec2_vpc_igw:
      vpc_id: "{{ vpc.vpc.id }}"
      tags:
        Name: wp_lab_igw
    register: igw

  - debug: var=igw

  - name: Create route table
    ec2_vpc_route_table:
      vpc_id: "{{ vpc.vpc.id }}"
      region: eu-central-1
      subnets:
        - "{{ subnet_left.subnet.id }}"
        - "{{ subnet_right.subnet.id }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ igw.gateway_id }}"
      tags:
        Name: wp_lab_rt
    register: route_table

  - debug: var=route_table

  - name: Create security group
    ec2_group:
      name: wp_lab_sg
      description: Security group for WP servers
      vpc_id: "{{ vpc.vpc.id }}"
      rules:
        - { proto: tcp, ports: 22,  cidr_ip: 0.0.0.0/0 }
        - { proto: tcp, ports: 80,  cidr_ip: 0.0.0.0/0 }
        - { proto: tcp, ports: 443, cidr_ip: 0.0.0.0/0 }
      tags:
        Name: wp_lab_sg
    register: security_group

  - debug: var=security_group
