---
- name: Create VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ vpc_region }}"
    tags:
      Name: "{{ vpc_name }}"
      ProjectID: "{{ project_id }}"
  register: vpc

- name: Create left subnet
  ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ subnet_left_cidr }}"
    region: "{{ vpc_region }}"
    az: "{{ subnet_left_az }}"
    tags:
      Name: "{{ subnet_left_name }}"
      ProjectID: "{{ project_id }}"
  register: subnet_left

- name: Create right subnet
  ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ subnet_right_cidr }}"
    region: "{{ vpc_region }}"
    az: "{{ subnet_right_az }}"
    tags:
      Name: "{{ subnet_right_name }}"
      ProjectID: "{{ project_id }}"
  register: subnet_right

- name: Create Internet gateway
  ec2_vpc_igw:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ vpc_region }}"
    tags:
      Name: "{{ igw_name }}"
      ProjectID: "{{ project_id }}"
  register: igw

- name: Create route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ vpc_region }}"
    subnets:
      - "{{ subnet_left.subnet.id }}"
      - "{{ subnet_right.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
    tags:
      Name: "{{ route_table_name }}"
      ProjectID: "{{ project_id }}"
  register: route_table

- name: Create ELB security group
  ec2_group:
    name: "{{ security_group_elb_name }}"
    description: Security group for ELB
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ vpc_region }}"
    rules:
      - { proto: tcp, ports: 80,  cidr_ip: 0.0.0.0/0 }
      - { proto: tcp, ports: 443, cidr_ip: 0.0.0.0/0 }
    tags:
      Name: "{{ security_group_elb_name }}"
      ProjectID: "{{ project_id }}"
  register: security_group_elb

- name: Create webservers security group
  ec2_group:
    name: "{{ security_group_web_name }}"
    description: Security group for WP servers
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ vpc_region }}"
    rules:
      - { proto: icmp, ports: -1, group_name: "{{ security_group_web_name }}" }
      - { proto: tcp, ports: 22,  cidr_ip: 0.0.0.0/0 }
      - { proto: tcp, ports: 80,  group_name: "{{ security_group_elb_name }}" }
      - { proto: tcp, ports: 443, group_name: "{{ security_group_elb_name }}" }
    tags:
      Name: "{{ security_group_web_name }}"
      ProjectID: "{{ project_id }}"
  register: security_group_web

- name: Create EFS security group
  ec2_group:
    name: "{{ security_group_efs_name }}"
    description: Security group for EFS access
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ vpc_region }}"
    rules:
      - { proto: tcp, ports: 2049,  group_name: "{{ security_group_web_name }}" }
    tags:
      Name: "{{ security_group_efs_name }}"
      ProjectID: "{{ project_id }}"
  register: security_group_efs

- name: Create RDS security group
  ec2_group:
    name: "{{ security_group_rds_name }}"
    description: Security group for RDS access
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ vpc_region }}"
    rules:
      - { proto: tcp, ports: 3306,  group_name: "{{ security_group_web_name }}" }
    tags:
      Name: "{{ security_group_rds_name }}"
      ProjectID: "{{ project_id }}"
  register: security_group_rds

- name: Create empty Application Load Balancer
  elb_application_lb:
    name: "{{ elb_name }}"
    region: "{{ vpc_region }}"
    security_groups:
      - "{{ security_group_elb.group_id }}"
    subnets:
      - "{{ subnet_left.subnet.id }}"
      - "{{ subnet_right.subnet.id }}"
    state: present
    tags:
      Name: "{{ elb_name }}"
      ProjectID: "{{ project_id }}"
  register: elb

- name: Create RDS subnet group
  rds_subnet_group:
    state: present
    name: "{{ rds_subnet_group_name }}"
    description: "{{ rds_subnet_group_name }}"
    region: "{{ vpc_region }}"
    subnets:
      - "{{ subnet_left.subnet.id }}"
      - "{{ subnet_right.subnet.id }}"
  register: rds_sg

- debug:
    msg: 
      - "The following two tasks will take 10-15 minutes to complete."
      - "Just relax and take a cup of tea, while we are preparing for the show."

- name: Create RDS instance
  rds_instance:
    region: "{{ vpc_region }}"
    engine: mysql
    engine_version: "{{ rds_engine_version }}"
    db_instance_identifier: "{{ rds_instance_id }}"
    db_instance_class: "{{ rds_instance_class }}"
    allocated_storage: "{{ rds_storage_alloc }}"
    db_subnet_group_name: "{{ rds_sg.subnet_group.db_subnet_group_name }}"
    vpc_security_group_ids: [ "{{ security_group_rds.group_id }}" ]
    username: "{{ rds_username }}"
    password: "{{ rds_password }}"
    publicly_accessible: no
    state: started
    tags:
      Name: "{{ rds_instance_id }}"
      ProjectID: "{{ project_id }}"
  register: rds_instance

- name: Create EFS
  efs:
    name: "{{ efs_name }}"
    region: "{{ vpc_region }}"
    targets:
      - subnet_id: "{{ subnet_left.subnet.id }}"
        security_groups: [ "{{ security_group_efs.group_id }}" ]
      - subnet_id: "{{ subnet_right.subnet.id }}"
        security_groups: [ "{{ security_group_efs.group_id }}" ]
    tags:
      Name: "{{ efs_name }}"
      ProjectID: "{{ project_id }}"
  register: efs

- name: Create EC2 keypair
  ec2_key:
    name: "{{ ssh_key_name }}"
    region: "{{ vpc_region }}"
  register: ssh_key

- name: Save private key (if generated)
  copy:
    content: "{{ ssh_key.key.private_key }}"
    dest: "{{ ssh_key_file }}"
    mode: 0600
  when: ssh_key.key.private_key is defined

- name: Create EC2 instance for the left subnet
  ec2_instance:
    name: "{{ ec2_instance_left_name }}"
    key_name: "{{ ssh_key_name }}"
    region: "{{ vpc_region }}"
    vpc_subnet_id: "{{ subnet_left.subnet.id }}"
    instance_type: "{{ ec2_instance_type }}"
    security_group: "{{ security_group_web.group_id }}"
    network:
      assign_public_ip: true
    image_id: "{{ ec2_instance_ami }}"
    state: running
    user_data: "{{ lookup('template', 'user_data.j2') }}"
    tags:
      Name: "{{ ec2_instance_left_name }}"
      ProjectID: "{{ project_id }}"
  register: ec2_instance_left

- name: Create EC2 instance for the right subnet
  ec2_instance:
    name: "{{ ec2_instance_right_name }}"
    key_name: "{{ ssh_key_name }}"
    region: "{{ vpc_region }}"
    vpc_subnet_id: "{{ subnet_right.subnet.id }}"
    instance_type: "{{ ec2_instance_type }}"
    security_group: "{{ security_group_web.group_id }}"
    network:
      assign_public_ip: true
    image_id: "{{ ec2_instance_ami }}"
    state: running
    user_data: "{{ lookup('template', 'user_data.j2') }}"
    tags:
      Name: "{{ ec2_instance_right_name }}"
      ProjectID: "{{ project_id }}"
  register: ec2_instance_right

- name: Create a target group for ELB
  elb_target_group:
    name: "{{ elb_target_group_name }}"
    protocol: http
    port: 80
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ vpc_region }}"
    health_check_protocol: http
    health_check_path: /
    successful_response_codes: "200"
    targets:
      - Id: "{{ ec2_instance_left.instances[0].instance_id }}"
        Port: 80
      - Id: "{{ ec2_instance_right.instances[0].instance_id }}"
        Port: 80
    state: present
    tags:
      Name: "{{ elb_target_group_name }}"
      ProjectID: "{{ project_id }}"
  register: elb_target_group

- name: Update Application Load Balancer
  elb_application_lb:
    name: "{{ elb_name }}"
    region: "{{ vpc_region }}"
    security_groups:
      - "{{ security_group_elb.group_id }}"
    subnets:
      - "{{ subnet_left.subnet.id }}"
      - "{{ subnet_right.subnet.id }}"
    listeners:
      - Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: forward
            TargetGroupName: "{{ elb_target_group_name }}"
    state: present
    tags:
      Name: "{{ elb_name }}"
      ProjectID: "{{ project_id }}"
  register: elb

- debug:
    msg: 
      - "Site address: http://{{ elb.dns_name }}"
      - "  Admin page: http://{{ elb.dns_name }}/wp-admin/"
      - "    Username: {{ wp_admin_user }}"
      - "    Password: {{ wp_admin_password }}"

- debug: 
    msg: 
      - "You may also manage EC2 nodes via ssh using the following commands:"
      - "    ssh -i {{ ssh_key_file }} admin@{{ec2_instance_left.instances[0].public_ip_address}}"
      - "    ssh -i {{ ssh_key_file }} admin@{{ec2_instance_right.instances[0].public_ip_address}}"
      - "RDS database management (from EC2 instances):"
      - "   mysql -h {{ rds_instance.endpoint.address }}"
      - "         -u {{ rds_username }}"
      - "         -p{{ rds_password }} "
  when: 
    - ec2_instance_left.instances[0].public_ip_address is defined
    - ec2_instance_right.instances[0].public_ip_address is defined

