---
- name: Delete EC2 instances
  ec2_instance:
    region: "{{ vpc_region }}"
    state: absent
    filters:
      "tag:Name": "{{ item }}"
      "tag:ProjectID": "{{ project_id }}"
  loop:
    - "{{ ec2_instance_left_name }}"
    - "{{ ec2_instance_right_name }}"

- name: Delete Application Load Balancer
  elb_application_lb:
    name: "{{ elb_name }}"
    state: absent

- name: Delete ELB target group
  elb_target_group:
    name: "{{ elb_target_group_name }}"
    state: absent

- name: Delete EFS
  efs:
    name: "{{ efs_name }}"
    state: absent

- name: Delete RDS instance
  community.aws.rds_instance:
    id: "{{ rds_instance_id }}"
    state: absent
    skip_final_snapshot: True

- name: Delete RDS subnet group
  rds_subnet_group:
    name: "{{ rds_subnet_group_name }}"
    state: absent

- name: Find VPC
  ec2_vpc_net_info:
    region: "{{ vpc_region }}"
    filters:
      "tag:Name": "{{ vpc_name }}"
      "tag:ProjectID": "{{ project_id }}"
  register: vpcs

- name: Delete VPC resources
  block:

    - name: Delete security groups
      ec2_group:
        name: "{{ item }}"
        vpc_id: "{{ vpcs.vpcs[0].vpc_id }}"
        state: absent
      loop:
        - "{{ security_group_efs_name }}"
        - "{{ security_group_rds_name }}"
        - "{{ security_group_web_name }}"
        - "{{ security_group_elb_name }}"

    - name: Delete subnets
      ec2_vpc_subnet:
        cidr: "{{ item }}"
        vpc_id: "{{ vpcs.vpcs[0].vpc_id }}"
        state: absent
      loop:
        - "{{ subnet_left_cidr }}"
        - "{{ subnet_right_cidr }}"

    - name: Delete route table
      ec2_vpc_route_table:
        vpc_id: "{{ vpcs.vpcs[0].vpc_id }}"
        region: "{{ vpc_region }}"
        tags:
          Name: "{{ route_table_name }}"
          ProjectID: "{{ project_id }}"
        state: absent

    - name: Delete Internet gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpcs.vpcs[0].vpc_id }}"
        tags:
          Name: "{{ igw_name }}"
          ProjectID: "{{ project_id }}"
        state: absent

  when: vpcs.vpcs[0].vpc_id is defined

- name: Delete VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ vpc_region }}"
    tags:
      Name: "{{ vpc_name }}"
      ProjectID: "{{ project_id }}"
    state: absent
