---
- name: Create VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ vpc_region }}"
  register: vpc

- debug: var=vpc

- name: Create left subnet
  ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ subnet_left_cidr }}"
    az: "{{ subnet_left_az }}"
    tags:
      Name: "{{ subnet_left_name }}"
  register: subnet_left

- debug: var=subnet_left

- name: Create right subnet
  ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ subnet_right_cidr }}"
    az: "{{ subnet_right_az }}"
    tags:
      Name: "{{ subnet_right_name }}"
  register: subnet_right

- debug: var=subnet_right

- name: Create Internet gateway
  ec2_vpc_igw:
    vpc_id: "{{ vpc.vpc.id }}"
    tags:
      Name: "{{ igw_name }}"
  register: igw

- debug: var=igw

- name: Create route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ vpc_region }}"
    subnets:
      - "{{ subnet_left.subnet.id }}"
      - "{{ subnet_right.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
    tags:
      Name: "{{ route_table_name }}"
  register: route_table

- debug: var=route_table

- name: Create security group
  ec2_group:
    name: "{{ security_group_name }}"
    description: Security group for WP servers
    vpc_id: "{{ vpc.vpc.id }}"
    rules:
      - { proto: tcp, ports: 22,  cidr_ip: 0.0.0.0/0 }
      - { proto: tcp, ports: 80,  cidr_ip: 0.0.0.0/0 }
      - { proto: tcp, ports: 443, cidr_ip: 0.0.0.0/0 }
    tags:
      Name: "{{ security_group_name }}"
  register: security_group

- debug: var=security_group
